# This is a docker compose file for the backend, not the website
services:
  bitcraftmap-api-1:
    container_name: bitcraftmap-api-1
    image: bitcraftmap-api:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:4001:4001"
    environment:
      SOCKET_ADDR: "0.0.0.0:4001"
      REGION: "1"
      TOKEN: "${TOKEN}"
  bitcraftmap-api-2:
    container_name: bitcraftmap-api-2
    image: bitcraftmap-api:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:4002:4002"
    environment:
      SOCKET_ADDR: "0.0.0.0:4002"
      REGION: "2"
      TOKEN: "${TOKEN}"
  bitcraftmap-api-3:
    container_name: bitcraftmap-api-3
    image: bitcraftmap-api:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:4003:4003"
    environment:
      SOCKET_ADDR: "0.0.0.0:4003"
      REGION: "3"
      TOKEN: "${TOKEN}"
  bitcraftmap-api-4:
    container_name: bitcraftmap-api-4
    image: bitcraftmap-api:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:4004:4004"
    environment:
      SOCKET_ADDR: "0.0.0.0:4004"
      REGION: "4"
      TOKEN: "${TOKEN}"
  bitcraftmap-api-5:
    container_name: bitcraftmap-api-5
    image: bitcraftmap-api:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:4005:4005"
    environment:
      SOCKET_ADDR: "0.0.0.0:4005"
      REGION: "5"
      TOKEN: "${TOKEN}"
  bitcraftmap-api-6:
    container_name: bitcraftmap-api-6
    image: bitcraftmap-api:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:4006:4006"
    environment:
      SOCKET_ADDR: "0.0.0.0:4006"
      REGION: "6"
      TOKEN: "${TOKEN}"
  bitcraftmap-api-7:
    container_name: bitcraftmap-api-7
    image: bitcraftmap-api:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:4007:4007"
    environment:
      SOCKET_ADDR: "0.0.0.0:4007"
      REGION: "7"
      TOKEN: "${TOKEN}"
  bitcraftmap-api-8:
    container_name: bitcraftmap-api-8
    image: bitcraftmap-api:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:4008:4008"
    environment:
      SOCKET_ADDR: "0.0.0.0:4008"
      REGION: "8"
      TOKEN: "${TOKEN}"
  bitcraftmap-api-9:
    container_name: bitcraftmap-api-9
    image: bitcraftmap-api:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:4009:4009"
    environment:
      SOCKET_ADDR: "0.0.0.0:4009"
      REGION: "9"
      TOKEN: "${TOKEN}"